version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
