name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm ember try:each --skip-cleanup
      - name: Build
        run: pnpm build

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18
          args: "--no-lockfile"
      - name: Run Tests
        run: pnpm ember try:each --skip-cleanup

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-4.12
          - ember-lts-5.4
          - ember-lts-5.8
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run Tests
        run: ./node_modules/.bin/ember try:each --skip-cleanup
        env:
          EMBER_SCENARIO: ${{ matrix.try-scenario }}
